const carData = [
    {
        "id": 1,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Exeter",
        "hourlyPrice": 10,
        "avalable": true,
        "image1": "assets/images/cars/acura_0.png",
        "image2": "assets/images/cars/acura_1.png",
        "image3": "assets/images/cars/acura_2.png",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 2,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Newcastle",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "assets/images/cars/land_rover_0.png",
        "image2": "assets/images/cars/land_rover_1.png",
        "image3": "assets/images/cars/land_rover_2.png",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 3,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Cambridge",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "assets/images/cars/alfa_romeo_c4_0.png",
        "image2": "assets/images/cars/alfa_romeo_c4_0.png",
        "image3": "assets/images/cars/alfa_romeo_c4_0.png",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 4,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Manchester",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 5,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 6,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Birmingham",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 7,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 8,
        "car_brand": "nissan",
        "type": "Small",
        "location": "London",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 9,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Sheffield",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 10,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Exeter",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 11,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 12,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Exeter",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 13,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Exeter",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 14,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 15,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Cambridge",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 16,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "London",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 17,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Sheffield",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 18,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Manchester",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 19,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Leeds",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 20,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Cambridge",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 21,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Sheffield",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 22,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 23,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Nottingham",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 24,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 25,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Leeds",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 26,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 27,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Birmingham",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 28,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Cambridge",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 29,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Sheffield",
        "hourlyPrice": 10,
        "avalable": true,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 30,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Liverpool",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 31,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Liverpool",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 32,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 33,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Manchester",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 34,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Liverpool",
        "hourlyPrice": 10,
        "avalable": true,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 35,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Newcastle",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 36,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 37,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Manchester",
        "hourlyPrice": 10,
        "avalable": true,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 38,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Exeter",
        "hourlyPrice": 30,
        "avalable": false,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 39,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Exeter",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 40,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 41,
        "car_brand": "fiat",
        "type": "Small",
        "location": "London",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 42,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 43,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Sheffield",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 44,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Exeter",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 45,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 46,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Birmingham",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 47,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Exeter",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 48,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Leeds",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 49,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 50,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 51,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Manchester",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 52,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Cambridge",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 53,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Nottingham",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 54,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 55,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 56,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Birmingham",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 57,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Manchester",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 58,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Liverpool",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 59,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 60,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Manchester",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 61,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Manchester",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 62,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "London",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 63,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 64,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Manchester",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 65,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Sheffield",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 66,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 67,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Manchester",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 68,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Exeter",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 69,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Leeds",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 70,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Cambridge",
        "hourlyPrice": 10,
        "avalable": false,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 71,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Newcastle",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 72,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Exeter",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 73,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 74,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Nottingham",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 75,
        "car_brand": "acura",
        "type": "Sport",
        "location": "London",
        "hourlyPrice": 10,
        "avalable": false,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 76,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Newcastle",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 77,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Birmingham",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 78,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Manchester",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 79,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Nottingham",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 80,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Liverpool",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 81,
        "car_brand": "fiat",
        "type": "Small",
        "location": "Newcastle",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "fiat_0.jpg",
        "image2": "fiat_1.jpg",
        "image3": "fiat_2.jpg",
        "engineSize": "1.4L",
        "engineSound": "Smooth"
    },
    {
        "id": 82,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Nottingham",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 83,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Birmingham",
        "hourlyPrice": 10,
        "avalable": false,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 84,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Sheffield",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 85,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Liverpool",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 86,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Leeds",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 87,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Exeter",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 88,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Manchester",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 89,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Sheffield",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 90,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Liverpool",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 91,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Manchester",
        "hourlyPrice": 30,
        "avalable": false,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 92,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 93,
        "car_brand": "honda",
        "type": "Hatchback",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "honda_0.jpg",
        "image2": "honda_1.jpg",
        "image3": "honda_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Quiet"
    },
    {
        "id": 94,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 95,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Exeter",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 96,
        "car_brand": "acura",
        "type": "Sport",
        "location": "Manchester",
        "hourlyPrice": 10,
        "avalable": true,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 97,
        "car_brand": "ferrari_spider_488",
        "type": "Sport",
        "location": "Manchester",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "ferrari_spider_488_0.jpg",
        "image2": "ferrari_spider_488_1.jpg",
        "image3": "ferrari_spider_488_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "V6"
    },
    {
        "id": 98,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Newcastle",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 99,
        "car_brand": "ford",
        "type": "Hatchback",
        "location": "Nottingham",
        "hourlyPrice": 25,
        "avalable": false,
        "image1": "ford_0.jpg",
        "image2": "ford_1.jpg",
        "image3": "ford_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 100,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Newcastle",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    },
    {
        "id": 101,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": false,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 102,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Leeds",
        "hourlyPrice": 40,
        "avalable": false,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 103,
        "car_brand": "land_rover",
        "type": "SUV",
        "location": "Manchester",
        "hourlyPrice": 40,
        "avalable": true,
        "image1": "land_rover_0.jpg",
        "image2": "land_rover_1.jpg",
        "image3": "land_rover_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "Powerful"
    },
    {
        "id": 104,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Exeter",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 105,
        "car_brand": "citroen",
        "type": "Electric",
        "location": "Cambridge",
        "hourlyPrice": 15,
        "avalable": true,
        "image1": "citroen_0.jpg",
        "image2": "citroen_1.jpg",
        "image3": "citroen_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Quiet"
    },
    {
        "id": 106,
        "car_brand": "acura",
        "type": "Sport",
        "location": "London",
        "hourlyPrice": 10,
        "avalable": false,
        "image1": "acura_0.jpg",
        "image2": "acura_1.jpg",
        "image3": "acura_2.jpg",
        "engineSize": "1.6L",
        "engineSound": "Powerful"
    },
    {
        "id": 107,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Sheffield",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 108,
        "car_brand": "nissan",
        "type": "Small",
        "location": "Exeter",
        "hourlyPrice": 30,
        "avalable": true,
        "image1": "nissan_0.jpg",
        "image2": "nissan_1.jpg",
        "image3": "nissan_2.jpg",
        "engineSize": "1.8L",
        "engineSound": "Smooth"
    },
    {
        "id": 109,
        "car_brand": "camaro",
        "type": "Small",
        "location": "Liverpool",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "camaro_0.jpg",
        "image2": "camaro_1.jpg",
        "image3": "camaro_2.jpg",
        "engineSize": "3.2L",
        "engineSound": "Powerful"
    },
    {
        "id": 110,
        "car_brand": "alfa_romeo",
        "type": "Hatchback",
        "location": "Birmingham",
        "hourlyPrice": 25,
        "avalable": true,
        "image1": "alfa_romeo_0.jpg",
        "image2": "alfa_romeo_1.jpg",
        "image3": "alfa_romeo_2.jpg",
        "engineSize": "2.3L",
        "engineSound": "V6"
    }

]
export default carData